# Generated by Django 4.2.16 on 2024-09-28 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_age_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShownVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=30, verbose_name='ID видео')),
                ('shown_at', models.DateTimeField(auto_now_add=True, verbose_name='Время показа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Показанное видео',
                'verbose_name_plural': 'Показанные видео',
            },
        ),
    ]
